### ISSUE TITLE
Typo: Withdraw

### ISSUE THREAD

**Issue by BenjaminPrice** [Loopring/neo-protocol#5]
Not a real bug. But, before it’s published you may want to fix the typo. 

‘withdrow’ -> ‘withdraw’

https://github.com/Loopring/neo-protocol/blob/4a3ab7f24e47e72499d73df138b9906101fbff0a/utils/LrnAirdropContract/LrnAirdropContract/Contract1.cs#L134

**Comment by BenjaminPrice** [comment]
Another spot with the same typo (different file)

https://github.com/Loopring/neo-protocol/blob/4a3ab7f24e47e72499d73df138b9906101fbff0a/utils/LrnAirdropContract/LrnAirdropContract/program.cs#L105

**Comment by BenjaminPrice** [comment]
There are a few other spots in the files linked. I suggest using find and replace.

**Comment by autumn84** [comment]
@BenjaminPrice we have accepted your suggestion, thank you very much.
